#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5

# yabai -m config window_border on
# yabai -m config window_border_width 3
# yabai -m config active_window_border_color 0xFF40FF00
# yabai -m config normal_window_border_color 0x00FFFFFF
# yabai -m config insert_feedback_color      0xffd75f5f

yabai -m space 1  --label one
yabai -m space 2  --label two
yabai -m space 3  --label three
yabai -m space 4  --label four
yabai -m space 5  --label five
yabai -m space 6  --label six
yabai -m space 7  --label seven
yabai -m space 8  --label eight
yabai -m space 9  --label nine
yabai -m space 10 --label ten
yabai -m space 11 --label eleven

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^Préférences Système$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="UTM" manage=off
yabai -m rule --add app="SentinelAgent" manage=off
yabai -m rule --add app="Safari" title="Général" manage=off
yabai -m rule --add app="Pycharm" manage=off
yabai -m rule --add app="Pycharm" title="^pre-categorisation.*" manage=on
yabai -m rule --add app="Scroll Reverser" manage=off
yabai -m rule --add app="Pritunl" manage=off

echo "yabai configuration loaded.."
