export COMPOSER_HOME="$HOME/.config/composer"
export COMPOSER_CACHE_DIR="$HOME/.cache/composer"
export _Z_DATA="$HOME/.local/share/z/data"
export SXHKD_SHELL="/bin/dash"
export MOB_WIP_COMMIT_MESSAGE="chore: End of Pablo's session [ci-skip]"
export MOB_TIMER="15"
